// orgId
import {
  AppointmentObject,
  ClientObject,
  OrgObject,
  UserObject,
} from "@lib/validations";

export const OrgData: OrgObject[] = [
  {
    orgId: "org0",
    name: "JASPER",
    subdomain: "jasper",
  },
  {
    orgId: "org1",
    name: "KENGEN",
    subdomain: "kengen",
  },
  {
    orgId: "org2",
    name: "CENTREGY",
    subdomain: "centregy",
  },
  {
    orgId: "org3",
    name: "EXOSPACE",
    subdomain: "exospace",
  },
  {
    orgId: "org4",
    name: "NEXGENE",
    subdomain: "nexgene",
  },
  {
    orgId: "org5",
    name: "GRACKER",
    subdomain: "gracker",
  },
  {
    orgId: "org6",
    name: "COMBOGENE",
    subdomain: "combogene",
  },
  {
    orgId: "org7",
    name: "ORBIXTAR",
    subdomain: "orbixtar",
  },
  {
    orgId: "org8",
    name: "MOREGANIC",
    subdomain: "moreganic",
  },
  {
    orgId: "org9",
    name: "TURNLING",
    subdomain: "turnling",
  },
  {
    orgId: "org10",
    name: "QIAO",
    subdomain: "qiao",
  },
  {
    orgId: "org11",
    name: "FARMAGE",
    subdomain: "farmage",
  },
  {
    orgId: "org12",
    name: "CINESANCT",
    subdomain: "cinesanct",
  },
  {
    orgId: "org13",
    name: "EVEREST",
    subdomain: "everest",
  },
  {
    orgId: "org14",
    name: "BITREX",
    subdomain: "bitrex",
  },
  {
    orgId: "org15",
    name: "TUBALUM",
    subdomain: "tubalum",
  },
  {
    orgId: "org16",
    name: "COMSTAR",
    subdomain: "comstar",
  },
  {
    orgId: "org17",
    name: "PRINTSPAN",
    subdomain: "printspan",
  },
  {
    orgId: "org18",
    name: "MARVANE",
    subdomain: "marvane",
  },
  {
    orgId: "org19",
    name: "EVENTEX",
    subdomain: "eventex",
  },
];

export const ClientsData: ClientObject[] = [
  {
    clientId: "client0",
    firstName: "Alyssa",
    lastName: "Sosa",
    gender: "female",
    email: "alyssasosa@eschoir.com",
    phone: "(817) 411-3652",
  },
  {
    clientId: "client1",
    firstName: "Ratliff",
    lastName: "Mcleod",
    gender: "male",
    email: "ratliffmcleod@eschoir.com",
    phone: "(907) 422-3623",
  },
  {
    clientId: "client2",
    firstName: "Sharp",
    lastName: "Byers",
    gender: "male",
    email: "sharpbyers@eschoir.com",
    phone: "(833) 538-3310",
  },
  {
    clientId: "client3",
    firstName: "Cross",
    lastName: "Browning",
    gender: "male",
    email: "crossbrowning@eschoir.com",
    phone: "(914) 418-3929",
  },
  {
    clientId: "client4",
    firstName: "Avery",
    lastName: "Bean",
    gender: "male",
    email: "averybean@eschoir.com",
    phone: "(879) 482-2717",
  },
  {
    clientId: "client5",
    firstName: "Isabel",
    lastName: "Oliver",
    gender: "female",
    email: "isabeloliver@eschoir.com",
    phone: "(908) 569-3150",
  },
  {
    clientId: "client6",
    firstName: "Rush",
    lastName: "Figueroa",
    gender: "male",
    email: "rushfigueroa@eschoir.com",
    phone: "(836) 414-2532",
  },
  {
    clientId: "client7",
    firstName: "Anna",
    lastName: "Armstrong",
    gender: "female",
    email: "annaarmstrong@eschoir.com",
    phone: "(847) 563-2723",
  },
  {
    clientId: "client8",
    firstName: "Holt",
    lastName: "Decker",
    gender: "male",
    email: "holtdecker@eschoir.com",
    phone: "(826) 426-3523",
  },
  {
    clientId: "client9",
    firstName: "Parker",
    lastName: "Rhodes",
    gender: "male",
    email: "parkerrhodes@eschoir.com",
    phone: "(819) 445-2064",
  },
  {
    clientId: "client10",
    firstName: "Corinne",
    lastName: "Blackburn",
    gender: "female",
    email: "corinneblackburn@eschoir.com",
    phone: "(913) 459-3994",
  },
  {
    clientId: "client11",
    firstName: "Oconnor",
    lastName: "Clemons",
    gender: "male",
    email: "oconnorclemons@eschoir.com",
    phone: "(843) 551-2631",
  },
  {
    clientId: "client12",
    firstName: "Amie",
    lastName: "Evans",
    gender: "female",
    email: "amieevans@eschoir.com",
    phone: "(931) 463-3219",
  },
  {
    clientId: "client13",
    firstName: "Harrell",
    lastName: "Doyle",
    gender: "male",
    email: "harrelldoyle@eschoir.com",
    phone: "(942) 425-2990",
  },
  {
    clientId: "client14",
    firstName: "Sherri",
    lastName: "Turner",
    gender: "female",
    email: "sherriturner@eschoir.com",
    phone: "(909) 594-2772",
  },
  {
    clientId: "client15",
    firstName: "Mindy",
    lastName: "Wright",
    gender: "female",
    email: "mindywright@eschoir.com",
    phone: "(878) 530-2433",
  },
  {
    clientId: "client16",
    firstName: "Kerri",
    lastName: "Short",
    gender: "female",
    email: "kerrishort@eschoir.com",
    phone: "(821) 528-2651",
  },
  {
    clientId: "client17",
    firstName: "Aurora",
    lastName: "Hutchinson",
    gender: "female",
    email: "aurorahutchinson@eschoir.com",
    phone: "(909) 555-3339",
  },
  {
    clientId: "client18",
    firstName: "Gallagher",
    lastName: "Hardin",
    gender: "male",
    email: "gallagherhardin@eschoir.com",
    phone: "(806) 461-2573",
  },
  {
    clientId: "client19",
    firstName: "Alyson",
    lastName: "Baldwin",
    gender: "female",
    email: "alysonbaldwin@eschoir.com",
    phone: "(811) 588-2546",
  },
];

export const UserData: UserObject[] = [
  {
    clerkId: "06174c89-2664-4228-9524-0ee0a85c5509",
    orgId: "org18",
    firstName: "Rosario",
    lastName: "Burke",
    email: "rosarioburke@zillidium.com",
    role: "member",
  },
  {
    clerkId: "81ee3551-1222-40e0-91b5-c5e1c4115019",
    orgId: "org8",
    firstName: "Sue",
    lastName: "Blevins",
    email: "sueblevins@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "5dd72c37-8d49-411d-9643-6e19d837dd75",
    orgId: "org15",
    firstName: "Zimmerman",
    lastName: "Gregory",
    email: "zimmermangregory@zillidium.com",
    role: "member",
  },
  {
    clerkId: "ee58aea3-0238-469b-92a2-81f947513f2b",
    orgId: "org4",
    firstName: "Rodriquez",
    lastName: "Murray",
    email: "rodriquezmurray@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "7fe8b259-4d78-4d1b-94a3-5ebc0816d9c8",
    orgId: "org16",
    firstName: "Karina",
    lastName: "Lang",
    email: "karinalang@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "e96d5e4a-e75c-4f0c-b877-1e7d8e53c680",
    orgId: "org11",
    firstName: "Gutierrez",
    lastName: "Russell",
    email: "gutierrezrussell@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "76919e45-f87d-45ef-a13e-09b654e6a844",
    orgId: "org3",
    firstName: "Mcdonald",
    lastName: "Hicks",
    email: "mcdonaldhicks@zillidium.com",
    role: "member",
  },
  {
    clerkId: "3e861c7a-59d9-43e8-9432-d4f4749b1e58",
    orgId: "org8",
    firstName: "Lou",
    lastName: "Solis",
    email: "lousolis@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "be86f36a-5b07-4f8f-b711-ec7c0b57540e",
    orgId: "org17",
    firstName: "Wheeler",
    lastName: "Patel",
    email: "wheelerpatel@zillidium.com",
    role: "member",
  },
  {
    clerkId: "b608ba81-aa8b-4b6e-aa85-7acf59ac4aa7",
    orgId: "org14",
    firstName: "Kaufman",
    lastName: "Albert",
    email: "kaufmanalbert@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "76f864f8-bed2-4eba-bf84-9e404b929052",
    orgId: "org10",
    firstName: "Hunter",
    lastName: "Sandoval",
    email: "huntersandoval@zillidium.com",
    role: "member",
  },
  {
    clerkId: "4f8e0898-1915-48f2-ae43-5ecc9df04749",
    orgId: "org11",
    firstName: "Amie",
    lastName: "Armstrong",
    email: "amiearmstrong@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "c6caf125-92dd-499b-8b81-41b9409a8c9d",
    orgId: "org17",
    firstName: "Knight",
    lastName: "Schmidt",
    email: "knightschmidt@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "54bd710f-5edc-4810-a8ef-1b9f990f5302",
    orgId: "org7",
    firstName: "Madge",
    lastName: "Mullins",
    email: "madgemullins@zillidium.com",
    role: "member",
  },
  {
    clerkId: "0fd7d1d0-14c3-4576-a67f-fe330cd7d00d",
    orgId: "org11",
    firstName: "Carrillo",
    lastName: "Caldwell",
    email: "carrillocaldwell@zillidium.com",
    role: "member",
  },
  {
    clerkId: "9b333d2e-444f-498a-90f9-f25dce2e3ca7",
    orgId: "org11",
    firstName: "Yvette",
    lastName: "Cooley",
    email: "yvettecooley@zillidium.com",
    role: "member",
  },
  {
    clerkId: "19f34cba-f295-4d45-89f1-90d14f2b7e24",
    orgId: "org10",
    firstName: "Amalia",
    lastName: "Pittman",
    email: "amaliapittman@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "fb6faa46-cf74-43f5-83a4-59566a597343",
    orgId: "org17",
    firstName: "Sears",
    lastName: "Stewart",
    email: "searsstewart@zillidium.com",
    role: "member",
  },
  {
    clerkId: "e0b8f763-7e98-4bac-a514-a25b0f30af50",
    orgId: "org10",
    firstName: "Raymond",
    lastName: "Woodard",
    email: "raymondwoodard@zillidium.com",
    role: "member",
  },
  {
    clerkId: "a51f84bd-36d7-4bb8-a546-3a6a2f0f55a9",
    orgId: "org14",
    firstName: "Camille",
    lastName: "Compton",
    email: "camillecompton@zillidium.com",
    role: "member",
  },
  {
    clerkId: "dba3af18-95af-4a08-a499-f02eb3a596a8",
    orgId: "org15",
    firstName: "Francisca",
    lastName: "Shannon",
    email: "franciscashannon@zillidium.com",
    role: "member",
  },
  {
    clerkId: "fa5b84fa-800c-4d28-9c52-762d80426c9b",
    orgId: "org14",
    firstName: "Shaffer",
    lastName: "Knight",
    email: "shafferknight@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "25b7db76-ca3d-444b-bdf3-98e2fd0bf14d",
    orgId: "org9",
    firstName: "Cara",
    lastName: "Wilson",
    email: "carawilson@zillidium.com",
    role: "member",
  },
  {
    clerkId: "ca0c8b75-8ec2-49ba-a2c8-84e669015b9c",
    orgId: "org4",
    firstName: "Deanne",
    lastName: "Dunlap",
    email: "deannedunlap@zillidium.com",
    role: "member",
  },
  {
    clerkId: "86a7cb11-e72f-480c-b207-e735dcb58341",
    orgId: "org11",
    firstName: "Misty",
    lastName: "Meyer",
    email: "mistymeyer@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "0eb138e0-2fc5-4e32-b88b-1d456521b7ca",
    orgId: "org0",
    firstName: "Adrienne",
    lastName: "Hayes",
    email: "adriennehayes@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "e4b0a516-26b5-42d4-b155-2910a46e1826",
    orgId: "org4",
    firstName: "Stacie",
    lastName: "Weaver",
    email: "stacieweaver@zillidium.com",
    role: "member",
  },
  {
    clerkId: "ed512a76-c44b-4340-8ab7-62e0939d0212",
    orgId: "org18",
    firstName: "Cummings",
    lastName: "Ellison",
    email: "cummingsellison@zillidium.com",
    role: "member",
  },
  {
    clerkId: "68e83737-1676-404f-91fe-c7b41be931c8",
    orgId: "org5",
    firstName: "Kaye",
    lastName: "Burch",
    email: "kayeburch@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "8e422fa9-390d-463c-81bc-9f7941cc29d9",
    orgId: "org5",
    firstName: "Kendra",
    lastName: "Coleman",
    email: "kendracoleman@zillidium.com",
    role: "member",
  },
  {
    clerkId: "7fa04aca-10b5-4b83-a9fb-0c78ad45f89d",
    orgId: "org9",
    firstName: "Serena",
    lastName: "Valenzuela",
    email: "serenavalenzuela@zillidium.com",
    role: "member",
  },
  {
    clerkId: "60cc2293-7c16-47d6-b38a-546294c70cb4",
    orgId: "org11",
    firstName: "Brianna",
    lastName: "Morin",
    email: "briannamorin@zillidium.com",
    role: "member",
  },
  {
    clerkId: "2ecf5a24-a6c0-4bd2-99e1-b0730942403f",
    orgId: "org18",
    firstName: "Natalie",
    lastName: "Hewitt",
    email: "nataliehewitt@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "99b9e567-50a0-451a-adce-5e75cf72bd24",
    orgId: "org16",
    firstName: "Wendy",
    lastName: "Ochoa",
    email: "wendyochoa@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "42866245-02c6-41cc-a032-a3956b078197",
    orgId: "org13",
    firstName: "Weeks",
    lastName: "Best",
    email: "weeksbest@zillidium.com",
    role: "member",
  },
  {
    clerkId: "cb1f5a6e-a001-47e6-ba51-9e20d978b3cd",
    orgId: "org1",
    firstName: "Rutledge",
    lastName: "Washington",
    email: "rutledgewashington@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "646650cb-636a-4cc9-9693-dda27a7e07d7",
    orgId: "org7",
    firstName: "Mcguire",
    lastName: "Lowe",
    email: "mcguirelowe@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "8f615bbf-06dc-4a28-8de8-5f6b48e14356",
    orgId: "org15",
    firstName: "Nadine",
    lastName: "Cameron",
    email: "nadinecameron@zillidium.com",
    role: "member",
  },
  {
    clerkId: "8783b9d6-c55d-4917-ae5d-c2b2bd16e6a5",
    orgId: "org1",
    firstName: "Jerri",
    lastName: "Sanford",
    email: "jerrisanford@zillidium.com",
    role: "admin",
  },
  {
    clerkId: "9d72b2c2-26a4-4555-bc94-6aad4e5bfe5d",
    orgId: "org15",
    firstName: "Ochoa",
    lastName: "Lewis",
    email: "ochoalewis@zillidium.com",
    role: "member",
  },
];

export const AppointmentsData: AppointmentObject[] = [
  {
    appointmentId: "appointment0",
    orgId: "org12",
    clientId: "client15",
    status: "confirmed",
    date: "2024-08-08",
    time: "07:11:40",
    note: "Et nulla aute ipsum laboris adipisicing irure eiusmod labore ut culpa Lorem culpa amet.",
  },
  {
    appointmentId: "appointment1",
    orgId: "org18",
    clientId: "client3",
    status: "completed",
    date: "2024-07-24",
    time: "07:36:23",
    note: "Magna commodo aliqua eiusmod dolor dolor qui sint deserunt non officia deserunt.",
  },
  {
    appointmentId: "appointment2",
    orgId: "org17",
    clientId: "client3",
    status: "confirmed",
    date: "2024-04-16",
    time: "07:20:27",
    note: "Excepteur occaecat do dolore laboris officia esse duis eiusmod cupidatat excepteur sit sint ea duis.",
  },
  {
    appointmentId: "appointment3",
    orgId: "org19",
    clientId: "client14",
    status: "canceled",
    date: "2024-01-18",
    time: "12:53:30",
    note: "Occaecat irure Lorem veniam consequat pariatur irure occaecat nulla.",
  },
  {
    appointmentId: "appointment4",
    orgId: "org9",
    clientId: "client18",
    status: "canceled",
    date: "2024-03-18",
    time: "11:49:44",
    note: "Enim aute deserunt ea deserunt minim dolor laborum qui.",
  },
  {
    appointmentId: "appointment5",
    orgId: "org17",
    clientId: "client3",
    status: "pending",
    date: "2024-02-19",
    time: "05:21:32",
    note: "Consectetur laborum voluptate occaecat qui.",
  },
  {
    appointmentId: "appointment6",
    orgId: "org3",
    clientId: "client15",
    status: "completed",
    date: "2024-06-02",
    time: "07:21:41",
    note: "Sunt aliqua adipisicing magna adipisicing duis est dolor cupidatat reprehenderit aliquip do sunt.",
  },
  {
    appointmentId: "appointment7",
    orgId: "org8",
    clientId: "client17",
    status: "canceled",
    date: "2024-02-02",
    time: "05:44:57",
    note: "Ut reprehenderit sit sint magna reprehenderit voluptate labore qui dolore.",
  },
  {
    appointmentId: "appointment8",
    orgId: "org7",
    clientId: "client1",
    status: "canceled",
    date: "2024-06-29",
    time: "10:52:24",
    note: "Minim cupidatat minim labore pariatur dolore anim laboris enim laboris ut consequat dolore.",
  },
  {
    appointmentId: "appointment9",
    orgId: "org17",
    clientId: "client6",
    status: "confirmed",
    date: "2024-06-24",
    time: "05:57:29",
    note: "Consequat Lorem Lorem enim aliquip enim adipisicing exercitation cupidatat duis ad enim magna.",
  },
  {
    appointmentId: "appointment10",
    orgId: "org10",
    clientId: "client12",
    status: "canceled",
    date: "2024-07-20",
    time: "07:22:43",
    note: "Ea culpa fugiat minim qui esse sint ullamco non dolore aute et ipsum.",
  },
  {
    appointmentId: "appointment11",
    orgId: "org14",
    clientId: "client18",
    status: "canceled",
    date: "2024-07-17",
    time: "05:19:09",
    note: "Dolore in commodo exercitation exercitation sunt.",
  },
  {
    appointmentId: "appointment12",
    orgId: "org9",
    clientId: "client11",
    status: "confirmed",
    date: "2024-02-23",
    time: "09:05:18",
    note: "Est exercitation mollit do consequat laborum magna voluptate.",
  },
  {
    appointmentId: "appointment13",
    orgId: "org11",
    clientId: "client17",
    status: "completed",
    date: "2024-04-17",
    time: "10:21:12",
    note: "Occaecat consectetur qui irure nisi id excepteur.",
  },
  {
    appointmentId: "appointment14",
    orgId: "org1",
    clientId: "client8",
    status: "confirmed",
    date: "2024-06-11",
    time: "07:19:31",
    note: "Quis reprehenderit laborum Lorem ut sunt proident labore eiusmod veniam aliquip ullamco ex ex ut.",
  },
  {
    appointmentId: "appointment15",
    orgId: "org17",
    clientId: "client11",
    status: "confirmed",
    date: "2024-03-22",
    time: "06:52:53",
    note: "Laborum cupidatat aute reprehenderit non esse et sunt incididunt.",
  },
  {
    appointmentId: "appointment16",
    orgId: "org18",
    clientId: "client18",
    status: "completed",
    date: "2024-06-02",
    time: "11:58:07",
    note: "Ex non commodo esse nulla culpa magna occaecat aute cupidatat duis laborum sint veniam.",
  },
  {
    appointmentId: "appointment17",
    orgId: "org16",
    clientId: "client17",
    status: "completed",
    date: "2024-01-26",
    time: "10:47:41",
    note: "Elit fugiat consectetur laborum exercitation incididunt sunt.",
  },
  {
    appointmentId: "appointment18",
    orgId: "org13",
    clientId: "client18",
    status: "confirmed",
    date: "2024-05-29",
    time: "11:33:48",
    note: "Eu id magna nulla magna officia id veniam laborum magna reprehenderit nulla aute.",
  },
  {
    appointmentId: "appointment19",
    orgId: "org3",
    clientId: "client15",
    status: "confirmed",
    date: "2024-08-06",
    time: "08:59:43",
    note: "Est incididunt quis eu eu cupidatat.",
  },
  {
    appointmentId: "appointment20",
    orgId: "org18",
    clientId: "client10",
    status: "completed",
    date: "2024-07-05",
    time: "10:27:03",
    note: "Aliqua reprehenderit commodo exercitation deserunt non aute non sunt in cupidatat.",
  },
  {
    appointmentId: "appointment21",
    orgId: "org4",
    clientId: "client7",
    status: "confirmed",
    date: "2024-03-08",
    time: "09:53:58",
    note: "Eu id reprehenderit adipisicing ex duis elit adipisicing irure.",
  },
  {
    appointmentId: "appointment22",
    orgId: "org1",
    clientId: "client19",
    status: "pending",
    date: "2024-01-28",
    time: "04:55:35",
    note: "Excepteur incididunt dolore laboris exercitation sunt sint cillum id minim eu laboris in aliqua laborum.",
  },
  {
    appointmentId: "appointment23",
    orgId: "org6",
    clientId: "client18",
    status: "completed",
    date: "2024-06-23",
    time: "04:08:19",
    note: "Excepteur aute in minim consectetur nisi velit mollit dolore Lorem fugiat do.",
  },
  {
    appointmentId: "appointment24",
    orgId: "org12",
    clientId: "client9",
    status: "pending",
    date: "2024-03-23",
    time: "08:58:06",
    note: "Nulla cillum sint Lorem ut non eu do labore aliqua reprehenderit eu.",
  },
  {
    appointmentId: "appointment25",
    orgId: "org1",
    clientId: "client11",
    status: "canceled",
    date: "2024-05-03",
    time: "11:19:56",
    note: "Dolor irure non non commodo cillum irure dolor mollit laboris quis id.",
  },
  {
    appointmentId: "appointment26",
    orgId: "org11",
    clientId: "client7",
    status: "canceled",
    date: "2024-08-16",
    time: "06:03:28",
    note: "Enim in commodo pariatur magna est id culpa ullamco proident.",
  },
  {
    appointmentId: "appointment27",
    orgId: "org3",
    clientId: "client17",
    status: "completed",
    date: "2024-02-26",
    time: "08:39:18",
    note: "Tempor anim pariatur labore velit deserunt non ut consequat.",
  },
  {
    appointmentId: "appointment28",
    orgId: "org19",
    clientId: "client4",
    status: "pending",
    date: "2024-05-01",
    time: "03:55:46",
    note: "Culpa ipsum mollit reprehenderit in duis elit quis.",
  },
  {
    appointmentId: "appointment29",
    orgId: "org2",
    clientId: "client6",
    status: "completed",
    date: "2024-03-11",
    time: "01:06:48",
    note: "Ullamco elit exercitation ullamco pariatur eiusmod culpa laboris proident enim.",
  },
  {
    appointmentId: "appointment30",
    orgId: "org8",
    clientId: "client4",
    status: "pending",
    date: "2024-08-21",
    time: "07:11:56",
    note: "In ex do voluptate ullamco nulla mollit incididunt veniam est do et consequat nostrud nulla.",
  },
  {
    appointmentId: "appointment31",
    orgId: "org5",
    clientId: "client6",
    status: "canceled",
    date: "2024-05-21",
    time: "12:21:50",
    note: "Eiusmod ullamco elit aute enim ut in velit minim occaecat minim proident sunt ipsum.",
  },
  {
    appointmentId: "appointment32",
    orgId: "org8",
    clientId: "client10",
    status: "pending",
    date: "2024-07-21",
    time: "09:29:04",
    note: "Quis tempor duis id velit cillum ea occaecat ullamco ad eu commodo officia occaecat incididunt.",
  },
  {
    appointmentId: "appointment33",
    orgId: "org19",
    clientId: "client0",
    status: "pending",
    date: "2024-04-04",
    time: "03:24:00",
    note: "Mollit laboris officia occaecat voluptate et minim do id pariatur.",
  },
  {
    appointmentId: "appointment34",
    orgId: "org17",
    clientId: "client12",
    status: "completed",
    date: "2024-05-01",
    time: "02:17:24",
    note: "Consectetur nisi ut enim occaecat aliquip sint laboris incididunt voluptate qui ipsum eiusmod duis.",
  },
  {
    appointmentId: "appointment35",
    orgId: "org16",
    clientId: "client14",
    status: "pending",
    date: "2024-01-19",
    time: "01:01:48",
    note: "Elit dolore amet duis officia quis.",
  },
  {
    appointmentId: "appointment36",
    orgId: "org5",
    clientId: "client13",
    status: "canceled",
    date: "2024-07-16",
    time: "10:32:58",
    note: "Ut sint cupidatat non dolore exercitation ea.",
  },
  {
    appointmentId: "appointment37",
    orgId: "org11",
    clientId: "client2",
    status: "completed",
    date: "2024-05-22",
    time: "02:47:09",
    note: "Proident dolor do in Lorem dolore exercitation reprehenderit reprehenderit id ex aliqua fugiat.",
  },
  {
    appointmentId: "appointment38",
    orgId: "org1",
    clientId: "client0",
    status: "pending",
    date: "2024-07-07",
    time: "05:56:47",
    note: "Nulla ipsum voluptate magna est eiusmod consectetur proident pariatur.",
  },
  {
    appointmentId: "appointment39",
    orgId: "org11",
    clientId: "client2",
    status: "pending",
    date: "2024-02-02",
    time: "09:24:41",
    note: "Proident fugiat voluptate commodo pariatur id eu tempor et reprehenderit proident sint incididunt fugiat.",
  },
];
