// orgId
import { AppointmentObject } from "@lib/validations";

export const UpcomingAppointmentsData: AppointmentObject[] = [
  {
    appointmentId: "a3f4b2e1",
    clientId: "Alice Johnson",
    date: "2021-12-22",
    time: "2:45 PM",
    status: "Completed",
    note: "Patient was late",
    orgId: "1",
  },
  {
    appointmentId: "5e8d2b1f",
    clientId: "Bob Brown",
    date: "2022-02-10",
    time: "11:30 AM",
    status: "Pending",
    note: "Patient was late",
    orgId: "2",
  },
  {
    appointmentId: "3c4d6e2a",
    clientId: "Jane Smith",
    date: "2022-01-15",
    time: "9:10 AM",
    status: "Canceled",
    note: "Patient was late",
    orgId: "1",
  },
  {
    appointmentId: "9f1e7c3b",
    clientId: "Charlie Davis",
    date: "2022-03-05",
    time: "4:20 PM",
    status: "Confirmed",
    note: "Patient was late",
    orgId: "2",
  },
  {
    appointmentId: "b7d8a5c6",
    clientId: "John Doe",
    date: "2022-04-12",
    time: "7:55 AM",
    status: "Completed",
    orgId: "2",
  },
  {
    appointmentId: "a3f4b2e1",
    clientId: "Alice Johnson",
    date: "2021-12-22",
    time: "2:45 PM",
    status: "Completed",
    orgId: "2",
  },
  {
    appointmentId: "5e8d2b1f",
    clientId: "Bob Brown",
    date: "2022-02-10",
    time: "11:30 AM",
    status: "Pending",
    orgId: "1",
  },
  {
    appointmentId: "3c4d6e2a",
    clientId: "Jane Smith",
    date: "2022-01-15",
    time: "9:10 AM",
    status: "Canceled",
    orgId: "1",
  },
  {
    appointmentId: "9f1e7c3b",
    clientId: "Charlie Davis",
    date: "2022-03-05",
    time: "4:20 PM",
    status: "Confirmed",
    orgId: "1",
  },
  {
    appointmentId: "b7d8a5c6",
    clientId: "John Doe",
    date: "2022-04-12",
    time: "7:55 AM",
    status: "Completed",
    orgId: "2",
  },
  {
    appointmentId: "a3f4b2e1",
    clientId: "Alice Johnson",
    date: "2021-12-22",
    time: "2:45 PM",
    status: "Completed",
    orgId: "2",
  },
  {
    appointmentId: "5e8d2b1f",
    clientId: "Bob Brown",
    date: "2022-02-10",
    time: "11:30 AM",
    status: "Pending",
    orgId: "3",
  },
  {
    appointmentId: "3c4d6e2a",
    clientId: "Jane Smith",
    date: "2022-01-15",
    time: "9:10 AM",
    status: "Canceled",
    orgId: "3",
  },
  {
    appointmentId: "9f1e7c3b",
    clientId: "Charlie Davis",
    date: "2022-03-05",
    time: "4:20 PM",
    status: "Confirmed",
    orgId: "3",
  },
  {
    appointmentId: "b7d8a5c6",
    clientId: "John Doe",
    date: "2022-04-12",
    time: "7:55 AM",
    status: "Completed",
    orgId: "3",
  },
];
